### ISSUE TITLE
Edit emails "to" subject bug

### ISSUE THREAD

**Issue by Chihui8199** [AY2021S2-CS2113-W10-2/tp#136]
![image](https://user-images.githubusercontent.com/62389756/114135808-5c444e80-993c-11eb-98bc-de6f1ac11779.png)

the error message that says that you can't send to that email but the email address is still being edited. 

The message also shows that emails are successfully edited

**Comment by FarmZH98** [comment]
ya my rationale behind it is to simulate real email system where you can edit to anything you like, but just cant send unless you change to a correct email address
