### ISSUE TITLE
tags won't be sent to receiver?

### ISSUE THREAD

**Issue by FarmZH98** [AY2021S2-CS2113-W10-2/tp#140]
I drafted an email, tag it and send it. However, when i login to receiver email account, I can't see the tags in the email. Are tags not supposed to be sent over to receiver?

**Comment by jalvinchan** [comment]
I am thinking that the tags is up to the recipient to set themselves and the tag is not linked to the emails. An example is like teachers may tag an email as work and send it to students but for the students they will tag it as school.

**Comment by FarmZH98** [comment]
yeah good point!
