### ISSUE TITLE
no empty space is allowed after';' should inform user

### ISSUE THREAD

**Issue by yanli1215** [AY2021S2-CS2113-W10-2/tp#148]
I think when sending to multiple users, users should be reminded more obviously that now empty space is allowed after'; '
<img width="574" alt="Screenshot 2021-04-10 at 5 41 07 PM" src="https://user-images.githubusercontent.com/60375112/114265634-8709d200-9a24-11eb-8aee-cfe35041730a.png">

**Comment by FarmZH98** [comment]
Regardless of the space after ";" is fine actually!
