### ISSUE TITLE
bugs in edit draft emails

### ISSUE THREAD

**Issue by yanli1215** [AY2021S2-CS2113-W10-2/tp#149]
<img width="708" alt="Screenshot 2021-04-10 at 5 48 01 PM" src="https://user-images.githubusercontent.com/60375112/114265755-2c24aa80-9a25-11eb-8d74-f75f3ae520a1.png">
program cannot move on

**Comment by FarmZH98** [comment]
erm, cannot type to/subject/content?

**Comment by yanli1215** [comment]
> erm, cannot type to/subject/content?


yep, cannot
