### ISSUE TITLE
first time registering an account always says errors

### ISSUE THREAD

**Issue by yanli1215** [AY2021S2-CS2113-W10-2/tp#150]
<img width="546" alt="Screenshot 2021-04-10 at 5 58 52 PM" src="https://user-images.githubusercontent.com/60375112/114266050-adc90800-9a26-11eb-8460-dc586aa619ec.png">

the format of the email is correct.
this problem only appears the first time adding a new account after the existing 3 accounts

**Comment by Chihui8199** [comment]
There needs to be a new line at the end of the file. User should not touch this file at all. You guys just be careful when pushing other version?
